title: Joseph M Zaborek
logo: "/images/Tom.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Systems Engineering Manager for Maxar's Space Engineering Department<br>
  Second description 
  <br>Father, Brother, Son, Homebrewer, and fledgling guitar player.<br>
  <a href="https://www.linkedin.com/in/joe-zaborek-1033b711/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
